### ISSUE TITLE
Can't set "Montreal" as the Favorite Team

### ISSUE THREAD

**Issue by mrawji** [eracknaphobia/plugin.video.nhlgcl#19]
With Montreal set as the favorite team, there's an error decoding the FAV_TEAM string.

This log is from commit af31a277dd5c0a358985bf6c7eca539279c3f681 (tag: v2021.1.21)

```
021-01-24 22:10:18.825 T:140222600963648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/addon.py", line 1, in <module>
                                                from resources.lib.nhl_tv import *
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/resources/lib/nhl_tv.py", line 1, in <module>
                                                from resources.lib.globals import *
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/resources/lib/globals.py", line 595, in <module>
                                                if FAV_TEAM != str(settings.getSetting("fav_team_name")):
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by micahg** [comment]
Seems like an intentional feature -- why would anyone want to select Montreal!?

**Comment by mrawji** [comment]
Well played, sir! After almost 3 decades of mediocrity, I am still here. I am not sure there's any hope left for me.

**Comment by micahg** [comment]
Well I cheer the leafs so your 3 decades seems but a blink of an eye ;) OK, sorry, I'm not actually heping the situation -- I'll shut up now.

**Comment by eracknaphobia** [comment]
I'll get a fix out for this soon.

**Comment by mrawji** [comment]
Thank you!
