### ISSUE TITLE
Favortite Team's recent games crashes when game is in progress

### ISSUE THREAD

**Issue by mrawji** [eracknaphobia/plugin.video.nhlgcl#21]
When your favorite team is currently playing, bringing up the "team's recent games" crashes.

```
2021-01-28 17:34:39.387 T:140182144464448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'linescore'
                                            Traceback (most recent call last):
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/addon.py", line 53, in <module>
                                                my_teams_games()
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/resources/lib/nhl_tv.py", line 581, in my_teams_games
                                                create_game_listitem(game, date['date'])
                                              File "/home/mrawji/.kodi/addons/plugin.video.nhlgcl/resources/lib/nhl_tv.py", line 88, in create_game_listitem
                                                (game['linescore']['currentPeriodTimeRemaining'], game['linescore']['currentPeriodOrdinal'])
                                            KeyError: 'linescore'
                                            -->End of Python script error report<--
```

**Comment by mrawji** [comment]
PR coming, just wrapping up testing.

**Comment by mrawji** [comment]
PR: https://github.com/eracknaphobia/plugin.video.nhlgcl/pull/22
